### ISSUE TITLE
Incorrect data type assumption on resource items

### ISSUE THREAD

**Issue by SwoopX** [dresden-elektronik/deconz-rest-plugin-v2#10]
## Describe the bug

The current DDF implementation partially assumes the wrong data type for incoming data This e.g. leads to the need to treat integer values as strings.

As an example serves the `windowopen` state of a Danfoss Ally thermostat. On zigbee level, that data is represented as `enum8` with values from 0 - 4. Using the below JS Code, the result will always be "Unknown".

```
switch (Attr.val) {
    case 0:
        Item.val = "Quarantine";
        break;
    case 1:
        Item.val = "Closed";
        break;
    case 2:
        Item.val = "Hold";
        break;
    case 3:
        Item.val = "Open";
        break;
    case 4:
        Item.val = "Open (external), closed (internal)";
        break;
    default:
        Item.val = "Unknown";
        break;
}
```

Presumably, the root cause is that the data type defined in `resource.cpp` for the respective resource item is `string`. However, this should be considered as the output data type only for consistency.

## Steps to reproduce the behavior

See above. Changing the case values to strings results in the expected behavior.

## Expected behavior

Enforce the defined data type for a resource item as output data type and leave the input data type untouched.

## Screenshots

![grafik](https://user-images.githubusercontent.com/4005212/140496673-b8e27a79-3b9c-496b-90e0-33c84254c388.png)

![grafik](https://user-images.githubusercontent.com/4005212/140497029-69e77236-1d45-45a0-95bc-4a8519e30d7f.png)

## Environment

 - Host system: Any
 - Running method: Any
 - Firmware version: 26720700 and below
 - deCONZ version: 2.13.1 and 2.13.0
 - Device: ConBee I / ConBee II / RaspBee I / RaspBee II
 - Do you use an USB extension cable: Not relevant
 - Is there any other USB or serial devices connected to the host system? If so: Which? Not relevant

## deCONZ Logs

N/A

## Additional context

N/A

**Comment by manup** [comment]
Should be fixed by now?

**Comment by SwoopX** [comment]
Ah, yes, forgot to close it :)
